// ------------------------------------------------------
// DVTk - The Healthcare Validation Toolkit (www.dvtk.org)
// Copyright © 2009 DVTk
// ------------------------------------------------------
// This file is part of DVTk.
//
// DVTk is free software; you can redistribute it and/or modify it under the terms of the GNU
// Lesser General Public License as published by the Free Software Foundation; either version 3.0
// of the License, or (at your option) any later version. 
// 
// DVTk is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
// the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
// General Public License for more details. 
// 
// You should have received a copy of the GNU Lesser General Public License along with this
// library; if not, see <http://www.gnu.org/licenses/>

using System;
//
// Documentation NameSpace Summaries used by documentation generation
//
namespace Dvtk
{
    /// <summary>
    /// <p>
    /// The main component interface for the Dicom Validation ToolKit.
    /// This assembly can be used to perform DICOM validation tests.
    /// </p>
    /// <p>
    /// The <c>Sessions</c> namespace defines various session classes.
    /// Validation tests are performed within the context of sessions.
    /// </p>
    /// <p>
    /// The <c>Events</c> namespace defines events to signal the user (integrating application) 
    /// about reports generated by the component.
    /// </p>
    /// <p>
    /// The <see cref="Setup"/> is an entry-point for the component. It is used to ensure that
    /// the component is properly initialized and terminated.
    /// </p>
    /// <p>
    /// The <c>Security</c> namespace is used to set certificates and credentials used
    /// within a test session.
    /// </p>
    /// <p>
    /// The <c>Certificates</c> namespace is used to create test certificates.
    /// </p>
    /// </summary>
    class NamespaceDoc { }
}

namespace Dvtk.Certificates
{
    /// <summary>
    /// Contains a certificate generator. Use this generator to create new certificate files.
    /// </summary>
    class NamespaceDoc { }
}

namespace Dvtk.Events
{
    /// <summary>
    /// <p>
    /// Events may be used to tightly couple a GUI application to the component.
    /// The events provide a continues progress about activities performed by the component 
    /// during the validation process.
    /// These activities have various levels.
    /// </p>
    /// <p>
    /// The listening application can subscribe to these events by means of a 
    /// <see cref="Dvtk.Events.ActivityReportEventHandler"/>.
    /// </p>
    /// </summary>
    class NamespaceDoc { }
}

namespace Dvtk.Security
{
    /// <summary>
    /// During communication over TCP/IP, the OpenSSL protocols may be used.
    /// This requires the use of certificates (public keys) and credentials (private keys).
    /// The classes within this namespace are used to set the certificates and credentials
    /// for the validation test session.
    /// </summary>
    class NamespaceDoc { }
}

namespace Dvtk.Sessions
{
    /// <summary>
    /// <p>
    /// Validation tests are performed within the context of sessions.
    /// There are three kinds of sessions supported by the component;
    /// <list type="bullet">
    /// <item><see cref="Dvtk.Sessions.ScriptSession"/></item>
    /// <item><see cref="Dvtk.Sessions.MediaSession"/></item>
    /// <item><see cref="Dvtk.Sessions.EmulatorSession"/></item>
    /// </list>
    /// </p>
    /// <p>
    /// There is a large collection of interfaces defined within this namespace.
    /// DO NOT BE INTIMIDATED by the number of interfaces. They just provide views
    /// on top of the session classes. A session class typically implements several interfaces.
    /// </p>
    /// </summary>
    class NamespaceDoc { }
}

