/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE definitionrestart( definitionin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int definitionleng;
extern FILE *definitionin, *definitionout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up definitiontext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up definitiontext again */ \
		} \
	while ( 0 )

#define unput(c) definitionunput( c, definitiontext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via definitionrestart()), so that the user can continue scanning by
	 * just pointing definitionin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when definitiontext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int definitionleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow definitionwrap()'s to do buffer switches
 * instead of setting up a fresh definitionin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void definitionrestart YY_PROTO(( FILE *input_file ));

void definition_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void definition_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE definition_create_buffer YY_PROTO(( FILE *file, int size ));
void definition_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void definition_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void definition_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER definition_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE definition_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE definition_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE definition_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer definition_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = definition_create_buffer( definitionin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = definition_create_buffer( definitionin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define definitionwrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *definitionin = (FILE *) 0, *definitionout = (FILE *) 0;
typedef int yy_state_type;
#define YY_FLEX_LEX_COMPAT
extern int definitionlineno;
int definitionlineno = 1;
extern char definitiontext[];


static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up definitiontext.
 */
#define YY_DO_BEFORE_ACTION \
	definitiontext_ptr = yy_bp; \
	definitiontext_ptr -= yy_more_len; \
	definitionleng = (int) (yy_cp - definitiontext_ptr); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	if ( definitionleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( definitiontext, definitiontext_ptr, definitionleng + 1 ); \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
static yyconst short int yy_acclist[200] =
    {   0,
      111,  109,  110,    5,  109,  110,    5,    7,  110,  109,
      110,    4,  109,  110,  109,  110,  106,  109,  110,  106,
      109,  110,  106,  109,  110,  106,  109,  110,  106,  109,
      110,   88,  109,  110,   87,  109,  110,   89,  109,  110,
      109,  110,   13,  109,  110,    9,  109,  110,   10,  109,
      110,  109,  110,  109,  110,  109,  110,   14,  109,  110,
      109,  110,  109,  110,  109,  110,  109,  110,  109,  110,
       15,  109,  110,  109,  110,  109,  110,  109,  110,    1,
      109,  110,    5,  109,  110,    3,    5,    6,    7,  110,
        4,  109,  110,    5,    7,    5,    7,  108,    4,  105,

      106,   16,   17,   18,   19,   90,   91,   20,   21,   22,
       23,   24,   11,   25,   26,   12,   27,   28,   29,   30,
       31,   32,   37,   33,   35,   95,   36,   34,   38,   39,
       40,   41,   42,   43,   44,   45,   53,   46,   47,   48,
       51,   49,   50,   52,    8,    5,    3,    5,    6,    4,
        2,  107,  103,  104,  104,  103,   94,   96,  102,   83,
       99,   93,   92,   98,  100,   85,  101,   77,   82,   79,
       97,   58,   73,   75,   81,   54,   56,   59,   60,   78,
       74,   76,   55,   57,   61,   62,   64,   63,   84,   65,
       67,   69,   86,   80,   66,   68,   70,   71,   72

    } ;

static yyconst short int yy_accept[325] =
    {   0,
        1,    1,    1,    2,    4,    7,   10,   12,   15,   17,
       20,   23,   26,   29,   32,   35,   38,   41,   43,   46,
       49,   52,   54,   56,   58,   61,   63,   65,   67,   69,
       71,   74,   76,   78,   80,   83,   86,   91,   94,   95,
       96,   98,   98,   99,   99,  100,  101,  102,  102,  102,
      103,  104,  105,  106,  107,  108,  109,  109,  110,  111,
      111,  112,  113,  113,  114,  115,  116,  117,  117,  117,
      117,  118,  119,  119,  120,  120,  121,  122,  122,  122,
      122,  122,  122,  123,  124,  125,  126,  127,  128,  129,
      130,  130,  131,  132,  132,  133,  134,  135,  136,  136,

      137,  137,  138,  139,  140,  141,  142,  143,  144,  145,
      145,  145,  145,  146,  147,  150,  150,  151,  152,  152,
      153,  153,  155,  156,  157,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  160,  160,  160,  160,
      160,  160,  160,  160,  160,  160,  160,  160,  161,  161,
      161,  161,  161,  161,  161,  161,  161,  161,  161,  161,
      161,  162,  162,  163,  164,  164,  164,  164,  164,  164,
      164,  164,  165,  165,  166,  166,  167,  167,  167,  167,

      167,  167,  167,  167,  167,  167,  167,  167,  168,  168,
      168,  168,  168,  168,  168,  169,  169,  169,  169,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  172,  172,  172,  172,  172,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,
      173,  174,  174,  175,  175,  176,  176,  177,  177,  178,
      178,  179,  180,  180,  180,  181,  181,  181,  181,  181,
      181,  181,  181,  182,  183,  183,  184,  185,  186,  187,
      187,  187,  187,  187,  187,  187,  187,  187,  188,  189,

      190,  190,  190,  191,  191,  192,  192,  193,  193,  193,
      194,  195,  196,  197,  198,  198,  198,  198,  198,  198,
      199,  199,  200,  200
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    7,    1,    8,    1,    1,    9,   10,   11,
       12,   13,   13,   13,   13,   13,   13,   14,    1,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,    1,
        1,   42,    1,    1,    1,    1,   43,   43,   43,   43,

       43,   43,    1,    1,    1,    1,    1,    1,    1,   44,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   45,
        1,    1,    1,    1,    1,    1,    1,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46
    } ;

static yyconst int yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    4,    1,    1,    1,    5,    5,    6,
        5,    5,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    7,
        1,    1,    1,    1,    7,    1
    } ;

static yyconst short int yy_base[333] =
    {   0,
        0,   45,  453,  454,   50,   53,   44,    0,   49,   36,
       49,   50,   45,   78,  436,  454,  435,   63,   59,   78,
       43,   56,   67,   44,   86,   70,   99,   75,  114,   78,
      136,  432,   93,  446,  454,  122,  127,  445,  132,  444,
      155,   77,  454,   63,    0,  166,  171,  176,  181,  454,
      454,  454,  454,  454,  454,  454,  425,  454,  454,  185,
      454,  454,  422,  454,  454,  454,  454,  412,  422,  414,
      454,  454,  421,  454,  418,  454,  454,  419,  402,  416,
      195,  400,  454,  454,  454,  454,  454,  454,  454,  454,
      413,  454,  454,  402,  454,  454,  454,  454,  398,  454,

      395,  454,  454,  454,  454,  454,  454,  454,  454,  403,
      396,  411,  454,  219,  165,  425,  424,  454,  118,  454,
      222,    0,    0,  227,  454,  408,  405,  398,  401,  391,
      385,  394,  383,  397,  382,  388,  386,  380,  395,  375,
      391,  376,  387,  370,  385,  384,  454,  370,  384,  367,
      380,  364,  370,  372,  395,  454,  367,  371,  365,  358,
      355,  361,  361,  349,  367,  366,  350,  454,  355,  350,
      356,  347,  360,  353,  358,  343,  342,  355,  348,  353,
      454,  352,  454,  454,  353,  341,  350,  362,  347,  334,
      345,  454,  343,  454,  344,  454,  333,  341,  336,  343,

      338,  329,  350,  349,  326,  337,  325,  454,  331,  344,
      343,  316,  341,  326,  454,  321,  324,  313,  454,  313,
      307,  306,  305,  306,  305,  302,  302,  454,  308,  301,
      300,  108,  299,  324,  301,  122,  310,  299,  306,  305,
      318,  111,  128,  454,  288,  291,  162,  163,  454,  263,
      177,  260,  264,  243,  251,  240,  259,  257,  256,  229,
      454,  230,  454,  229,  454,  226,  454,  227,  454,  226,
      454,  454,  225,  193,  454,  234,  235,  236,  219,  218,
      217,  228,  454,  454,  216,  454,  454,  454,  454,  216,
      217,  184,  176,  194,  208,  209,  174,  454,  454,  454,

      142,  130,  454,  128,  454,  122,  454,  121,  109,  454,
      454,  454,  454,  454,   98,   80,  102,   61,  212,  454,
       51,  454,  454,  270,  277,  284,  289,  294,  300,  307,
      314,  319
    } ;

static yyconst short int yy_def[333] =
    {   0,
      323,    1,  323,  323,  323,  324,  325,  326,  323,  327,
      328,  328,   12,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  324,  329,  323,  324,
      324,  325,  323,  330,  326,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  331,  329,  323,  330,  323,
      323,   49,  332,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  331,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,    0,  323,  323,  323,  323,  323,  323,  323,
      323,  323
    } ;

static yyconst short int yy_nxt[501] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    9,   10,   11,
       12,   13,   14,    4,   15,   16,   17,   18,    4,   19,
       20,   21,   22,    4,    4,   23,    4,   24,   25,   26,
       27,   28,    4,    4,   29,   30,   31,   32,   33,    4,
        4,   34,    4,    4,    4,   35,   36,   37,   43,   48,
       38,   39,   39,   39,   41,   39,   41,   46,   46,   46,
       46,   46,   48,   48,   52,  120,   60,   43,   50,   51,
       67,   68,   69,   70,   76,   49,   71,   81,   53,   77,
       49,   43,  322,   72,   56,   44,   47,   47,   47,   47,
       47,   48,   57,   61,  319,   62,   73,   58,   59,   63,

       82,   74,   75,   78,   90,   64,  100,   79,   91,  318,
      111,  101,   65,   66,  112,  317,   80,   83,   44,   84,
      323,   85,   43,  114,  115,   39,   86,  116,   41,   39,
       41,  316,   87,   39,   39,   39,   88,   89,   92,  315,
      249,   93,  250,  261,   94,  262,   95,  254,   96,   97,
      255,   98,  314,  313,   99,  102,   41,   39,   41,  312,
      263,  103,  264,  104,  311,  105,   39,   39,   39,  106,
      107,  108,  310,  109,   46,   46,   46,   46,   46,   47,
       47,   47,   47,   47,  121,  121,  121,  121,  121,  122,
      122,  122,  122,  122,  267,  269,  268,  270,  123,  123,

      123,  123,  123,  123,  126,  309,  127,  128,  129,  272,
      302,  273,  141,  130,  142,  143,  144,  301,  145,  131,
      114,  115,   39,  124,  116,  289,  303,  290,  304,  146,
      121,  121,  121,  121,  121,  124,  124,  124,  124,  124,
      305,  307,  306,  308,  320,  300,  321,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  156,  279,  278,  277,  124,
       40,   40,   40,   40,   40,   40,   40,   42,  276,   42,
       42,   42,   42,   42,   45,  275,   45,   45,   45,   45,
       45,   47,   47,  274,  271,   47,   47,   47,  266,   47,

      117,  117,  117,  117,  117,  117,  117,  119,  119,  119,
      119,  119,  119,  119,  155,  155,  155,  155,  155,  155,
      155,  123,  265,  123,  123,  260,  259,  258,  257,  256,
      253,  252,  251,  248,  247,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  185,  118,  184,  183,

      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  118,  118,  154,  153,
      152,  151,  150,  149,  148,  147,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  125,  323,  118,  113,  110,
       55,   54,  323,    3,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323

    } ;

static yyconst short int yy_chk[501] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    7,   10,
        2,    5,    5,    5,    6,    6,    6,    9,    9,    9,
        9,    9,   11,   12,   13,   44,   19,   44,   11,   12,
       21,   21,   21,   22,   24,   10,   22,   26,   13,   24,
       10,   42,  321,   22,   18,    7,   14,   14,   14,   14,
       14,   14,   18,   19,  318,   20,   23,   18,   18,   20,

       26,   23,   23,   25,   28,   20,   30,   25,   28,  317,
       33,   30,   20,   20,   33,  316,   25,   27,   42,   27,
      119,   27,  119,   36,   36,   36,   27,   36,   37,   37,
       37,  315,   27,   39,   39,   39,   27,   27,   29,  309,
      232,   29,  232,  242,   29,  242,   29,  236,   29,   29,
      236,   29,  308,  306,   29,   31,   41,   41,   41,  304,
      243,   31,  243,   31,  302,   31,  115,  115,  115,   31,
       31,   31,  301,   31,   46,   46,   46,   46,   46,   47,
       47,   47,   47,   47,   48,   48,   48,   48,   48,   49,
       49,   49,   49,   49,  247,  248,  247,  248,   49,   49,

       49,   49,   49,   49,   60,  297,   60,   60,   60,  251,
      293,  251,   81,   60,   81,   81,   81,  292,   81,   60,
      114,  114,  114,   49,  114,  274,  294,  274,  294,   81,
      121,  121,  121,  121,  121,  124,  124,  124,  124,  124,
      295,  296,  295,  296,  319,  291,  319,  290,  285,  282,
      281,  280,  279,  278,  277,  276,  273,  270,  268,  266,
      264,  262,  260,  259,  258,  121,  257,  256,  255,  124,
      324,  324,  324,  324,  324,  324,  324,  325,  254,  325,
      325,  325,  325,  325,  326,  253,  326,  326,  326,  326,
      326,  327,  327,  252,  250,  327,  328,  328,  246,  328,

      329,  329,  329,  329,  329,  329,  329,  330,  330,  330,
      330,  330,  330,  330,  331,  331,  331,  331,  331,  331,
      331,  332,  245,  332,  332,  241,  240,  239,  238,  237,
      235,  234,  233,  231,  230,  229,  227,  226,  225,  224,
      223,  222,  221,  220,  218,  217,  216,  214,  213,  212,
      211,  210,  209,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  195,  193,  191,  190,  189,  188,
      187,  186,  185,  182,  180,  179,  178,  177,  176,  175,
      174,  173,  172,  171,  170,  169,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  155,  154,  153,

      152,  151,  150,  149,  148,  146,  145,  144,  143,  142,
      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,
      131,  130,  129,  128,  127,  126,  117,  116,  112,  111,
      110,  101,   99,   94,   91,   82,   80,   79,   78,   75,
       73,   70,   69,   68,   63,   57,   40,   38,   34,   32,
       17,   15,    3,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323

    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up definitiontext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() (yy_more_flag = 1)
#define YY_MORE_ADJ yy_more_len
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char definitiontext[YYLMAX];
char *definitiontext_ptr;
#line 1 "definition_lex.l"
#define INITIAL 0
#line 4 "definition_lex.l"
// Part of Dvtk Libraries - Internal Native Library Code
// Copyright © 2001-2006
// Philips Medical Systems NL B.V., Agfa-Gevaert N.V.

#ifdef _WINDOWS
#pragma warning (disable : 4102)
#pragma warning (disable : 4273)
#pragma warning (disable : 4786)
#endif

/*
 *	contains the Lexer for the ODD output
 */
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <stdio.h>

#define YY_NEVER_INTERACTIVE 1 

#include "Iglobal.h"		// Global component interface
#include "Ilog.h"			// Log component interface
#include "Icondition.h"		// Condition component interface
#include "definition_parse.cpp.h"

#define ODD_DIM_OF(a) (sizeof((a))/sizeof((a)[0]))
#define RETURN(a) tokenType = (a); return((a));
#define definitionlval  definitionlval
#define definitionerror definitionerror
#define yywarn  definitionwarn

void yywarn(char *msg);
void definitionerror(char* msg);

//Export variables for logging purposes
LOG_CLASS* definitionfilelogger_ptr = 0;
UINT       definitionerrors = 0;
UINT       definitionwarnings = 0;

//Extern variables
extern bool definitionParseOnly;

//Variables to keep track of current line and the 
//position of the token in this line 
static char prev_linebuf[MAXIMUM_LINE_LENGTH];
static char curr_linebuf[MAXIMUM_LINE_LENGTH];

bool IsHex(char, int*);

static int tokenType = '\0';
char*   End_ptr;

typedef struct {
    int tokenType;
	char* tokenName;
} TOKEN_MAP_STRUCT;


static TOKEN_MAP_STRUCT tokenTable[] = {
{ T_SYSTEM, "T_SYSTEM"},
{ T_DEFINE, "T_DEFINE"},
{ T_ENDDEFINE, "T_ENDDEFINE"},
{ T_METASOPCLASS, "T_METASOPCLASS"},
{ T_SOPCLASS, "T_SOPCLASS"},
{ T_MODULE,	"T_MODULE"},
{ T_MACRO, "T_MACRO"},
{ T_INCLUDEMACRO, "T_INCLUDEMACRO"},
{ T_SQ, "T_SQ"},		
{ T_AND, "T_AND"},
{ T_OR,  "T_OR"},
{ T_NOT, "T_NOT"},
{ T_PRESENT, "T_PRESENT"},
{ T_VALUE, "T_VALUE"},
{ T_EMPTY, "T_EMPTY"},
{ T_TRUE, "T_TRUE"},  
{ T_FALSE, "T_FALSE"},  
{ T_EQUAL, "T_EQUAL"},
{ T_LESS, "T_LESS"},
{ T_GREATER, "T_GREATER"},
{ T_LESS_OR_EQUAL, "T_LESS_OR_EQUAL"},
{ T_GREATER_OR_EQUAL, "T_GREATER_OR_EQUAL"},
{ T_WEAK, "T_WEAK"},
{ T_WARN, "T_WARN"},
{ STRING, "STRING"},
{ INTEGER, "INTEGER"},
{ HEX, "HEX"},
{ COMMANDFIELD, "COMMANDFIELD"},
{ TYPE, "TYPE"},
{ USAGE, "USAGE"},
{ VALUETYPE, "VALUETYPE"},
{ VR, "VR"}
};



/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int definitionwrap YY_PROTO(( void ));
#else
extern int definitionwrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void definitionunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef definitiontext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int definitioninput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( definitiontext, definitionleng, 1, definitionout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( definitionin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( definitionin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, definitionin )) == 0) \
		  && ferror( definitionin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int definitionlex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after definitiontext and definitionleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( definitionleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(definitiontext[definitionleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 102 "definition_lex.l"


	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! definitionin )
			definitionin = stdin;

		if ( ! definitionout )
			definitionout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				definition_create_buffer( definitionin, YY_BUF_SIZE );

		definition_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_more_len = 0;
		if ( yy_more_flag )
			{
			yy_more_len = definitionleng;
			yy_more_flag = 0;
			}
		yy_cp = yy_c_buf_p;

		/* Support of definitiontext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 324 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 454 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < definitionleng; ++yyl )
				if ( definitiontext[yyl] == '\n' )
					++definitionlineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 103 "definition_lex.l"
{ /* skip charcters from 80H - FFH */ 
						}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "definition_lex.l"
{ /* skip comment lines */ 
						}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 107 "definition_lex.l"
{ /* skip empty lines */ 
						}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 109 "definition_lex.l"
{ /* skip comment */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 110 "definition_lex.l"
{ /* skip white space */ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 111 "definition_lex.l"
{ /* skip empty lines */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 113 "definition_lex.l"
{ 
                          // skip newlines  
                          //Reset token position and
						  //save the next line
						  strcpy(prev_linebuf, curr_linebuf);
						  strcpy(curr_linebuf, definitiontext+1);
						  yyless(1); // give back all but the \n to rescan 
                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 121 "definition_lex.l"
{ /* continuation line */ 
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 124 "definition_lex.l"
{ definitionlval.valueType = ATTR_VAL_TYPE_DEFINED;     RETURN(VALUETYPE); 	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 125 "definition_lex.l"
{ definitionlval.valueType = ATTR_VAL_TYPE_ENUMERATED;  RETURN(VALUETYPE);  }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 126 "definition_lex.l"
{ definitionlval.valueType = ATTR_VAL_TYPE_DEFINED_LIST;     RETURN(VALUETYPE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 127 "definition_lex.l"
{ definitionlval.valueType = ATTR_VAL_TYPE_ENUMERATED_LIST;  RETURN(VALUETYPE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 129 "definition_lex.l"
{ definitionlval.usage = MOD_USAGE_C; RETURN(USAGE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 130 "definition_lex.l"
{ definitionlval.usage = MOD_USAGE_M; RETURN(USAGE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 131 "definition_lex.l"
{ definitionlval.usage = MOD_USAGE_U; RETURN(USAGE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 133 "definition_lex.l"
{ definitionlval.type = ATTR_TYPE_1C; RETURN(TYPE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 134 "definition_lex.l"
{ definitionlval.type = ATTR_TYPE_2C; RETURN(TYPE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 135 "definition_lex.l"
{ definitionlval.type = ATTR_TYPE_3C; RETURN(TYPE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 136 "definition_lex.l"
{ definitionlval.type = ATTR_TYPE_3R; RETURN(TYPE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 138 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_AE; RETURN(VR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 139 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_AS; RETURN(VR); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 140 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_AT; RETURN(VR); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 141 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_CS; RETURN(VR); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 142 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_DA; RETURN(VR); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 143 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_DS; RETURN(VR); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 144 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_DT; RETURN(VR); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 145 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_FD; RETURN(VR); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 146 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_FL; RETURN(VR); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 147 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_IS; RETURN(VR); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_LO; RETURN(VR); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 149 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_LT; RETURN(VR); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 150 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_OB; RETURN(VR); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 151 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_OF; RETURN(VR); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 152 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_OW; RETURN(VR); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 153 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_OL; RETURN(VR); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 154 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_OV; RETURN(VR); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 155 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_OD; RETURN(VR); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 156 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_PN; RETURN(VR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 157 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_SH; RETURN(VR); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 158 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_SL; RETURN(VR); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 159 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_SQ; RETURN(T_SQ); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 160 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_SS; RETURN(VR); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 161 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_ST; RETURN(VR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_SV; RETURN(VR); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 163 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_TM; RETURN(VR); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 164 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_UI; RETURN(VR); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 165 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_UL; RETURN(VR); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 166 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_UN; RETURN(VR); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 167 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_US; RETURN(VR); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 168 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_UT; RETURN(VR); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 169 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_UR; RETURN(VR); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 170 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_UV; RETURN(VR); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 171 "definition_lex.l"
{ definitionlval.vr = ATTR_VR_UC; RETURN(VR); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 173 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CECHO_RQ;         RETURN(COMMANDFIELD); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 174 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CECHO_RSP;        RETURN(COMMANDFIELD); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 175 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CFIND_RQ;         RETURN(COMMANDFIELD); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 176 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CFIND_RSP;        RETURN(COMMANDFIELD); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 177 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CGET_RQ;          RETURN(COMMANDFIELD); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 178 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CGET_RSP;         RETURN(COMMANDFIELD); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 179 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CMOVE_RQ;         RETURN(COMMANDFIELD); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 180 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CMOVE_RSP;        RETURN(COMMANDFIELD); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 181 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CSTORE_RQ;        RETURN(COMMANDFIELD); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 182 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CSTORE_RSP;       RETURN(COMMANDFIELD); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 183 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_CCANCEL_RQ;       RETURN(COMMANDFIELD); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 184 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NACTION_RQ;       RETURN(COMMANDFIELD); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 185 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NACTION_RSP;      RETURN(COMMANDFIELD); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 186 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NCREATE_RQ;       RETURN(COMMANDFIELD); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 187 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NCREATE_RSP;      RETURN(COMMANDFIELD); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 188 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NDELETE_RQ;       RETURN(COMMANDFIELD); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 189 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NDELETE_RSP;      RETURN(COMMANDFIELD); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 190 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NEVENTREPORT_RQ;  RETURN(COMMANDFIELD); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 191 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NEVENTREPORT_RSP; RETURN(COMMANDFIELD); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 192 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NGET_RQ;          RETURN(COMMANDFIELD); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 193 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NGET_RSP;         RETURN(COMMANDFIELD); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 194 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NSET_RQ;          RETURN(COMMANDFIELD); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 195 "definition_lex.l"
{ definitionlval.commandField = DIMSE_CMD_NSET_RSP;         RETURN(COMMANDFIELD); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 198 "definition_lex.l"
{ RETURN(T_DEFINE); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 199 "definition_lex.l"
{ RETURN(T_ENDDEFINE); } 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 200 "definition_lex.l"
{ RETURN(T_SYSTEM); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 201 "definition_lex.l"
{ RETURN(T_METASOPCLASS); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 202 "definition_lex.l"
{ RETURN(T_SOPCLASS); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 203 "definition_lex.l"
{ RETURN(T_MODULE); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 204 "definition_lex.l"
{ RETURN(T_ITEM); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 205 "definition_lex.l"
{ RETURN(T_INCLUDEITEM); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 206 "definition_lex.l"
{ RETURN(T_MACRO); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 207 "definition_lex.l"
{ RETURN(T_INCLUDEMACRO); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 208 "definition_lex.l"
{ RETURN(T_EQUAL); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 209 "definition_lex.l"
{ RETURN(T_LESS); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 210 "definition_lex.l"
{ RETURN(T_GREATER); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 211 "definition_lex.l"
{ RETURN(T_LESS_OR_EQUAL);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 212 "definition_lex.l"
{ RETURN(T_GREATER_OR_EQUAL);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 213 "definition_lex.l"
{ RETURN(T_WEAK);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 214 "definition_lex.l"
{ RETURN(T_WARN);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 215 "definition_lex.l"
{ RETURN(T_AND);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 216 "definition_lex.l"
{ RETURN(T_OR);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 217 "definition_lex.l"
{ RETURN(T_NOT);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 218 "definition_lex.l"
{ RETURN(T_PRESENT);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 219 "definition_lex.l"
{ RETURN(T_EMPTY);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 220 "definition_lex.l"
{ RETURN(T_TRUE);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 221 "definition_lex.l"
{ RETURN(T_FALSE);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 222 "definition_lex.l"
{ RETURN(T_VALUE);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 224 "definition_lex.l"
{
                            strcpy(definitionlval.string, definitiontext);
                            RETURN(STRING);
						}
	YY_BREAK
case 103:
#line 231 "definition_lex.l"
case 104:
YY_RULE_SETUP
#line 231 "definition_lex.l"
{ 
                            definitionlval.hex  = strtoul(definitiontext, &End_ptr, 16);
                            RETURN(HEX); 
						}
	YY_BREAK
case 105:
#line 236 "definition_lex.l"
case 106:
YY_RULE_SETUP
#line 236 "definition_lex.l"
{ 
                            definitionlval.integer = atoi(definitiontext); 
							RETURN(INTEGER); 
						}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 240 "definition_lex.l"
{ 
                            for (definitionleng = definitionleng-2; definitionleng >= 0; definitionleng--)
							{
						        unput(definitiontext[definitionleng]); /* concatenate line */ 
							}
                        }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 246 "definition_lex.l"
{ 
                            if ((definitionleng-2) >= sizeof(definitionlval.string))
						    {
						        yywarn("STRING too long!!! truncated") ;
			                    definitionleng = sizeof(definitionlval.string) +1 ;
						    }
						    memcpy(definitionlval.string, &definitiontext[1], definitionleng-2); 
                            definitionlval.string[definitionleng-2] = '\0';
						    RETURN(STRING);
						}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 256 "definition_lex.l"
{ 
                            RETURN(definitiontext[0]); 
						}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 259 "definition_lex.l"
ECHO;
	YY_BREAK
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - definitiontext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed definitionin at a new source and called
			 * definitionlex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = definitionin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = definitiontext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = definitiontext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( definitionwrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * definitiontext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = definitiontext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					definitiontext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = definitiontext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = definitiontext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of definitionlex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = definitiontext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - definitiontext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - definitiontext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			definitionrestart( definitionin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	definitiontext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = definitiontext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 324 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 324 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 323);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void definitionunput( int c, register char *yy_bp )
#else
static void definitionunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up definitiontext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--definitionlineno;

	definitiontext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int definitioninput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			definitiontext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( definitionwrap() )
						{
						yy_c_buf_p =
						definitiontext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return definitioninput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = definitiontext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in definitioninput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve definitiontext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');
	if ( yy_current_buffer->yy_at_bol )
		++definitionlineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void definitionrestart( FILE *input_file )
#else
void definitionrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = definition_create_buffer( definitionin, YY_BUF_SIZE );

	definition_init_buffer( yy_current_buffer, input_file );
	definition_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void definition_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void definition_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	definition_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (definitionwrap()) processing, but the only time this flag
	 * is looked at is after definitionwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void definition_load_buffer_state( void )
#else
void definition_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	definitiontext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	definitionin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE definition_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE definition_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in definition_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in definition_create_buffer()" );

	b->yy_is_our_buffer = 1;

	definition_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void definition_delete_buffer( YY_BUFFER_STATE b )
#else
void definition_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void definition_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void definition_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	definition_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void definition_flush_buffer( YY_BUFFER_STATE b )
#else
void definition_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		definition_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE definition_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE definition_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in definition_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	definition_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE definition_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE definition_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return definition_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE definition_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE definition_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in definition_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = definition_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in definition_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up definitiontext. */ \
		definitiontext[definitionleng] = yy_hold_char; \
		yy_c_buf_p = definitiontext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		definitionleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef definitiontext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	definitionlex();
	return 0;
	}
#endif
#line 259 "definition_lex.l"


void definitionerror(char *errmsg)
{
	if ( definitionfilelogger_ptr)
	{
		definitionfilelogger_ptr->text(LOG_ERROR, 1, "lineno: %d %s: ",
									   definitionlineno,
									   errmsg);
		definitionfilelogger_ptr->text(LOG_NONE, 1, "Current line: ");
		definitionfilelogger_ptr->text(LOG_NONE, 1, "%-50s...",curr_linebuf);
	}

    //Switch to parse only mode and try to find more errors
    definitionParseOnly = true;
	definitionerrors++;
	
	if (definitionerrors > 10)
	{
		if ( definitionfilelogger_ptr)
		{
			definitionfilelogger_ptr->text(LOG_ERROR, 1, "Unable to recover from previous errors. Stopping...");
		}
		exit(1);
	}
}

void definitionerror(char *errmsg, bool PrintCurrentLine)
{
    char linebuf[MAXIMUM_LINE_LENGTH];
	if (PrintCurrentLine)
	{
        strcpy(linebuf, curr_linebuf);
	}
	else
	{
		strcpy(linebuf, prev_linebuf);
	}

	if ( definitionfilelogger_ptr)
	{
		definitionfilelogger_ptr->text(LOG_ERROR, 1, "lineno: %d %s: ",
									   definitionlineno,
									   errmsg);
		definitionfilelogger_ptr->text(LOG_NONE, 1, "Current line: ");
		definitionfilelogger_ptr->text(LOG_NONE, 1, "%-50s...",curr_linebuf);
	}

    //Switch to parse only mode and try to find more errors
    definitionParseOnly = true;
	definitionerrors++;
}

void yywarn(char *msg)
{
	if ( definitionfilelogger_ptr)
	{
		definitionfilelogger_ptr->text(LOG_WARNING, 1, "lineno: %d %s: ",
									   definitionlineno,
									   msg);
		definitionfilelogger_ptr->text(LOG_NONE, 1, "Current line: ");
		definitionfilelogger_ptr->text(LOG_NONE, 1, "%-50s...",curr_linebuf);
	}

	definitionwarnings++;
}

void yywarn(char *msg, bool PrintCurrentLine)
{
    char linebuf[MAXIMUM_LINE_LENGTH];
	if (PrintCurrentLine)
	{
        strcpy(linebuf, curr_linebuf);
	}
	else
	{
		strcpy(linebuf, prev_linebuf);
	}

	if ( definitionfilelogger_ptr)
	{
		definitionfilelogger_ptr->text(LOG_WARNING, 1, "lineno: %d %s: ",
									   definitionlineno,
									   msg);
		definitionfilelogger_ptr->text(LOG_NONE, 1, "Current line: ");
		definitionfilelogger_ptr->text(LOG_NONE, 1, "%-50s...",curr_linebuf);
	}

	definitionwarnings++;
}

bool IsHex(char digit, int *value)
{
	bool isHex = true;
	
    if (isdigit(digit)) 
	{
		*value = digit - '0';
	}
	else if (('a' <= digit) && (digit <= 'f')) 
	{
		*value = digit - 'W';
	}
	else if (('A' <= digit) && (digit <= 'F')) 
	{
		*value = digit - '7';
	}
	else 
	{
		isHex = false;
	}

	return isHex;
}
