// ------------------------------------------------------
// DVTk - The Healthcare Validation Toolkit (www.dvtk.org)
// Copyright © 2009 DVTk
// ------------------------------------------------------
// This file is part of DVTk.
//
// DVTk is free software; you can redistribute it and/or modify it under the terms of the GNU
// Lesser General Public License as published by the Free Software Foundation; either version 3.0
// of the License, or (at your option) any later version. 
// 
// DVTk is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
// the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
// General Public License for more details. 
// 
// You should have received a copy of the GNU Lesser General Public License along with this
// library; if not, see <http://www.gnu.org/licenses/>

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2032.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;

namespace Dvtk.IheActors.Hl7.WebService.Generation
{
	/// <remarks/>
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name="MessageGenerationSOAP11Binding", Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov")]
	public class MessageGeneration : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
		/// <remarks/>
		public MessageGeneration(System.String url)
		{
			this.Url = url + "/MessageGeneration";
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getErrorDescription", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("getErrorDescriptionResponse", Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
		public getErrorDescriptionResponse getErrorDescription([System.Xml.Serialization.XmlElementAttribute("getErrorDescription", Namespace="")] getErrorDescription getErrorDescription1) 
		{
			object[] results = this.Invoke("getErrorDescription", new object[] {
																				   getErrorDescription1});
			return ((getErrorDescriptionResponse)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BegingetErrorDescription(getErrorDescription getErrorDescription1, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getErrorDescription", new object[] {
																			getErrorDescription1}, callback, asyncState);
		}
    
		/// <remarks/>
		public getErrorDescriptionResponse EndgetErrorDescription(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((getErrorDescriptionResponse)(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setGenerationContext", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("setGenerationContextResponse", Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
		public setGenerationContextResponse setGenerationContext([System.Xml.Serialization.XmlElementAttribute("setGenerationContext", Namespace="")] setGenerationContext setGenerationContext1) 
		{
			object[] results = this.Invoke("setGenerationContext", new object[] {
																					setGenerationContext1});
			return ((setGenerationContextResponse)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginsetGenerationContext(setGenerationContext setGenerationContext1, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("setGenerationContext", new object[] {
																			 setGenerationContext1}, callback, asyncState);
		}
    
		/// <remarks/>
		public setGenerationContextResponse EndsetGenerationContext(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((setGenerationContextResponse)(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:generate", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("generateResponse", Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
		public generateResponse generate([System.Xml.Serialization.XmlElementAttribute("generate", Namespace="")] generate generate1) 
		{
			object[] results = this.Invoke("generate", new object[] {
																		generate1});
			return ((generateResponse)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult Begingenerate(generate generate1, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("generate", new object[] {
																 generate1}, callback, asyncState);
		}
    
		/// <remarks/>
		public generateResponse Endgenerate(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((generateResponse)(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setProfile", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("setProfileResponse", Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
		public setProfileResponse setProfile([System.Xml.Serialization.XmlElementAttribute("setProfile", Namespace="")] setProfile setProfile1) 
		{
			object[] results = this.Invoke("setProfile", new object[] {
																		  setProfile1});
			return ((setProfileResponse)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginsetProfile(setProfile setProfile1, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("setProfile", new object[] {
																   setProfile1}, callback, asyncState);
		}
    
		/// <remarks/>
		public setProfileResponse EndsetProfile(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((setProfileResponse)(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setFixedData", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlElementAttribute("setFixedDataResponse", Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
		public setFixedDataResponse setFixedData([System.Xml.Serialization.XmlElementAttribute("setFixedData", Namespace="")] setFixedData setFixedData1) 
		{
			object[] results = this.Invoke("setFixedData", new object[] {
																			setFixedData1});
			return ((setFixedDataResponse)(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BeginsetFixedData(setFixedData setFixedData1, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("setFixedData", new object[] {
																	 setFixedData1}, callback, asyncState);
		}
    
		/// <remarks/>
		public setFixedDataResponse EndsetFixedData(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((setFixedDataResponse)(results[0]));
		}
    
		/// <remarks/>
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getMessages", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
		[return: System.Xml.Serialization.XmlArrayAttribute("getMessagesResponse", Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
		[return: System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types", IsNullable=false)]
		public string[] getMessages([System.Xml.Serialization.XmlElementAttribute("getMessages", Namespace="")] getMessages getMessages1) 
		{
			object[] results = this.Invoke("getMessages", new object[] {
																		   getMessages1});
			return ((string[])(results[0]));
		}
    
		/// <remarks/>
		public System.IAsyncResult BegingetMessages(getMessages getMessages1, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("getMessages", new object[] {
																	getMessages1}, callback, asyncState);
		}
    
		/// <remarks/>
		public string[] EndgetMessages(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string[])(results[0]));
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class getErrorDescription 
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class getMessages 
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class setFixedDataResponse 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool @return;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class setFixedData 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string param0;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class setProfileResponse 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool @return;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class setProfile 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string param0;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class generateResponse 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool @return;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class generate 
	{
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class setGenerationContextResponse 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public bool @return;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class setGenerationContext 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string param0;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://MessageGeneration.generation.ws.hl7.nist.gov/types")]
	public class getErrorDescriptionResponse 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public string @return;
	}
}