// ------------------------------------------------------
// DVTk - The Healthcare Validation Toolkit (www.dvtk.org)
// Copyright © 2009 DVTk
// ------------------------------------------------------
// This file is part of DVTk.
//
// DVTk is free software; you can redistribute it and/or modify it under the terms of the GNU
// Lesser General Public License as published by the Free Software Foundation; either version 3.0
// of the License, or (at your option) any later version. 
// 
// DVTk is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
// the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
// General Public License for more details. 
// 
// You should have received a copy of the GNU Lesser General Public License along with this
// library; if not, see <http://www.gnu.org/licenses/>

using System;
using System.IO;

namespace Dvtk.IheActors.Bases
{

	/// <summary>
	/// Summary description for RootedBaseDirectory.
	/// </summary>
	public class RootedBaseDirectory
	{
		/// <summary>
		/// Get the full pathname. The given pathname my already be full in which case it is just returned.
		/// Otherwise the full pathname is generated by prefixing the pathname with the full (rooted) base
		/// directory.
		/// </summary>
		/// <param name="rootedBaseDirectory">Full (rooted) base directory.</param>
		/// <param name="pathname">Pathname - maybe rooted or relative.</param>
		/// <returns>Full (rooted) pathname.</returns>
		public static System.String GetFullPathname(System.String rootedBaseDirectory, System.String pathname)
		{
			System.String fullPathname = System.String.Empty;

			// check if the pathname given is rooted (ie full)
			if (System.IO.Path.IsPathRooted(pathname) == true)
			{
				// just return full pathname
				fullPathname = pathname;
			}
			else
			{
				// check that the rootedBaseDirectory is really rooted
				if (System.IO.Path.IsPathRooted(rootedBaseDirectory) == false)
				{
					System.String message = System.String.Format("\"{0]\" is not a rooted base directory.", rootedBaseDirectory);
					throw new System.Exception(message);
				}

				// generate full pathname by prefixing with application base directory
				fullPathname = rootedBaseDirectory + "\\" + pathname;
			}

			return fullPathname;
		}
	}  
}
