using System;
using System.Collections.Generic;
using System.Text;
using System.Xml.XPath;

namespace Dvtk.Dicom.AttributeLayer.Specification
{
    /// <summary>
    ///  Common functionality for the Module, Macro and SequenceItem classes.
    /// </summary>
    public abstract class AttributesAndMacros: List<IAttributeOrMacro>
    {
        #region - Internal methods -
        // --------------------------------
        // - Begin internal methods region -
        // --------------------------------

        /// <summary>
        /// Add Attribute and Macros instances using a raw xml file (that is generated by the ODD).
        /// </summary>
        /// <param name="parentNode">The parent node for the attributes and macros.</param>
        internal void AddAttributesAndMacros(XPathNavigator parentNode)
        {
            //
            // Add attributes.
            //

            XPathNodeIterator attributeNodes = parentNode.Select("Attribute");

            foreach (XPathNavigator attributeNode in attributeNodes)
            {
                Attribute attribute = Attribute.Create(attributeNode, this);
                this.Add(attribute);
            }


            //
            // Add macros.
            //

            XPathNodeIterator macroNodes = parentNode.Select("Macro");

            foreach (XPathNavigator macroNode in macroNodes)
            {
                Macro macro = Macro.Create(macroNode, this);
                this.Add(macro);
            }
        }

        /// <summary>
        /// Create a string representation of the path of this instance.
        /// </summary>
        /// <param name="prefix">The prefix to use of identation.</param>
        /// <returns>The string representation.</returns>
        internal abstract string ToString2(string prefix);

        /// <summary>
        /// Create a string representation of the path of this instance.
        /// </summary>
        /// <returns>The string representation.</returns>
        internal abstract string ToString3();

        // ------------------------------
        // - End internal methods region -
        // ------------------------------
        #endregion



        #region - Public methods -
        // -------------------------------
        // - Begin public methods region -
        // -------------------------------

        /// <summary>
        /// Create an Attribute structure from the Module/Macro/Sequence Item structure.
        /// </summary>
        /// <param name="attributes">The list to add the Attributes to.</param>
        public virtual void CreateAttributeStructure(SortedAttributeList attributes)
        {
            foreach (IAttributeOrMacro attributeOrMacro in this)
            {
                attributeOrMacro.CreateAttributeStructure(attributes);
            }
        }

        // -----------------------------
        // - End public methods region -
        // -----------------------------
        #endregion
    }
}
