// ------------------------------------------------------
// DVTk - The Healthcare Validation Toolkit (www.dvtk.org)
// Copyright © 2009 DVTk
// ------------------------------------------------------
// This file is part of DVTk.
//
// DVTk is free software; you can redistribute it and/or modify it under the terms of the GNU
// Lesser General Public License as published by the Free Software Foundation; either version 3.0
// of the License, or (at your option) any later version. 
// 
// DVTk is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even
// the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser
// General Public License for more details. 
// 
// You should have received a copy of the GNU Lesser General Public License along with this
// library; if not, see <http://www.gnu.org/licenses/>

using System;
//
// Documentation NameSpace Summaries used by documentation generation
//
namespace DvtkData
{
    /// <summary>
    /// The classes within the <c>DvtkData</c> namespace are the data-classes that represent
    /// dicom messages and dul messages as well as validation data generated by the Dicom Validation Tool.
    /// </summary>
    class NamespaceDoc {}
}

namespace DvtkData.Activities
{
    /// <summary>
    /// Activities are used internally by the DVTK component to 
    /// report validation activities to the connection application layer.
    /// <br></br>
    /// These classes should not be directly used by the end-user.
    /// </summary>
    class NamespaceDoc {}
}

namespace DvtkData.Collections
{
    /// <summary>
    /// In many cases we might like to extend the collection classes provided by the framework. 
    /// Maybe we need to ensure that only objects of certain types are stored in the collection 
    /// or we need a different sorting algorithm. 
    /// Either way, custom collection classes will de-/serialize properly as long as they 
    /// implement IEnumerable or ICollection and, of course, we supply enough information 
    /// about the types stored inside the collection. Keep in mind that only the items that 
    /// can be accessed through the interfaces are serialized, 
    /// public properties and fields are not, unless they return a class 
    /// that itself implements ICollection. 
    /// There is another caveat when you implement your own container classes: 
    /// The implementation of the XmlSerializer requires the collection to have 
    /// a default accessor, even though ICollection does not require it. 
    /// In VB.Net a default accessor is implemented as an Item property with a single 
    /// parameter of type Integer. In C# it is implemented as an indexer. 
    /// The syntax for an indexer resembles a read-only property, but it uses 
    /// the square brackets around the parameter.
    /// <br></br>
    /// These collection classes are internally used by the component.
    /// <br></br>
    /// In .Net 2.x (Whidbey) the <c>System.Collections</c> namespace will 
    /// support templated strong-typed collections. 
    /// We may improve this part of the component to use that mechanism.
    /// </summary>
    class NamespaceDoc {}
}

namespace DvtkData.Dimse
{
    /// <summary>
    /// This namespace contains data classes related to the DICOM communication-layer;
    /// DIMSE (Dicom Messaging Service Element).
    /// </summary>
    class NamespaceDoc {}
}

namespace DvtkData.Dul
{
    /// <summary>
    /// This namespace contains data classes related to the DICOM communication-layer;
    /// DUL (Dicom Upper Layer).
    /// </summary>
    class NamespaceDoc {}
}

namespace DvtkData.Media
{
    /// <summary>
    /// This namespace contains data classes that represent DICOM media files and their
    /// contents.
    /// </summary>
    class NamespaceDoc {}
}

namespace DvtkData.Results
{
    /// <summary>
    /// This namespace contains data classes used to represent the results of the 
    /// Dicom Validation Tool validation process. 
    /// <br></br>
    /// These classes are the output of the Dicom Validation Toolkit.
    /// <br></br>
    /// Many of these classes are public. However these classes are only public to allow
    /// serialization into an XML output document. These classes should not be used directly
    /// by the end-user. The classes should not be instantiated by the end-user.
    /// </summary>
    class NamespaceDoc {}
}

namespace DvtkData.Validation
{
    /// <summary>
    /// This namespace contains data classes used to represent the results of the 
    /// Dicom Validation Tool validation process. 
    /// <br></br>
    /// These classes are the output of the Dicom Validation Toolkit.
    /// <br></br>
    /// Many of these classes are public. However these classes are only public to allow
    /// serialization into an XML output document. These classes should not be used directly
    /// by the end-user. The classes should not be instantiated by the end-user.
    /// </summary>
    class NamespaceDoc {}
}

